fix: nix shell build issue (semgrep/semgrep-proprietary#4762)
When building semgrep from the development shell, we started getting:
```
Error: Files /nix/store/xl3i0wmzhj02nbamlv44szajz11wk2px-tls-lwt-2.0.2/lib/ocaml/5.3.0/site-lib/tls-lwt/tls_lwt.cmxa
       and /nix/store/r8jkafascbcfj21r9ch8j1aarj7agwp1-lwt-5.7.0/lib/ocaml/5.3.0/site-lib/lwt/unix/lwt_unix.cmxa
       make inconsistent assumptions over implementation Lwt_unix
```
or similar. I'm not 100% sure of the source of the issue, but it seems like one of our dev dependencies (e.g. ocaml-lsp) started leaking its own deps. This [issue](https://github.com/tweag/opam-nix/issues/22) seems to be similar to what we experienced. The solution was to add `doNixSupport = false` to all dev dependencies, so they don't drag the cmi files they might have used into the path. 

Test plan:
I modified the shell tests to build the shell AND then run `make core`. Previously they would only make the shell but not actually try making the core. This will cause the job to run a little longer but that shouldn't block anyone.

synced from Pro 5488796e238f85792cafa69c00fb9804e71ecc40