fix(UFile): handle interrupted system calls during reads (semgrep/semgrep-proprietary#4547)
We semi-frequently see the `Osemgrep multi subcommands (e2e) > named pipe as target` test fail owing to having an EINTR delivered to the test process:

```
• Exception raised by the test:
 Unix_error: Interrupted system call read 
 Raised by primitive operation at Unix.read in file "unix.ml", line 275, characters 7-33
 Called from UFile.Legacy.read_file.loop in file "OSS/libs/commons/UFile.ml", line 82, characters 12-38
 Called from Stdlib__Fun.protect in file "fun.ml", line 34, characters 8-15
 Re-raised at Stdlib__Fun.protect in file "fun.ml", line 39, characters 6-52
 Called from Common.protect in file "OSS/libs/commons/Common.ml", line 53, characters 6-31
 Called from UTmp.replace_named_pipe_by_regular_file_if_needed in file "OSS/libs/commons/UTmp.ml", line 130, characters 17-37
...
```

[Being](https://github.com/ocaml/ocaml/blob/trunk/otherlibs/unix/unix_unix.ml#L273-L276) a thin wrapper around the C wrapper, `Unix.read` doesn't do any sophisticated error handling like retrying on an EINTR.  This patch does the bare minimum: if we are interrupted whilst in a `read` call, we just retry the read.  this is in line with the usual way for application code to handle this signal (e.g. [python](https://peps.python.org/pep-0475/#status-in-python-3-4), [C](https://blog.reverberate.org/2011/04/eintr-and-pc-loser-ing-is-better-case.html).).

Test plan:

I tried writing a unit test for this, but of course there's a fair amount of nondeterminism in this problem, and testo did not seem to like me setting up a signal handler as part of the test harness (it would sort of work with `-j0` but not otherwise, mysteriously).  This is not the end of the world, though.  We'll test this by no longer observing that that flaky test fails.  If it still appears after this patch, then this patch was not doing the right thing.

synced from Pro 085ce3431dadcb8bcf97e73f0ebb8e361acb89d1